### ISSUE TITLE
Sizing and alignment of pic in home page about section could be better

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#21]
Right now the cutout picture of Pat in the About section on the home page is great...but as the screen narrows, it gets awkwardly small. The picture looks really appropriate when it is its full size but as it gets small, it looks like Pat is peeking in in a rather comical way. I'd like to make sure it is properly sized for narrower screens.

Additionally, on every size after the narrow break point where that section's content stacks vertically, her image should be aligned right due to the right edge of her picture being cut off. And there may be similar sizing issues there too. She shouldn't shrink quite so much.

**Comment by d4mation** [comment]
Do you have an idea at which size this is happening? I changed my viewport all over the place and she appears to stay aligned-right and within the frame even at very small viewports for me.

![image](https://cloud.githubusercontent.com/assets/7770631/19807920/51dd007e-9cf0-11e6-932a-cf9a0cc157d2.png)

**Comment by brashrebel** [comment]
Just using Chrome on my mac I was resizing the window manually. Just tested, same result.

**Comment by d4mation** [comment]
Is this what you're talking about?

![image](https://cloud.githubusercontent.com/assets/7770631/19813951/16360894-9d0a-11e6-9733-d1213cb6fd0c.png)

It seems to happen at the same breakpoint as #18. I'll have to make Medium Screen specific fixes for these.

**Comment by brashrebel** [comment]
Yeah basically. She gets pretty small and the smaller she gets, the sillier it looks I think. Plus for me on the stacked width, she's still aligned left.

**Comment by joelworsham** [comment]
Could it be solved by simply starting her much bigger? Like in the mock:

<img width="1160" alt="screen shot 2016-10-28 at 3 34 41 pm" src="https://cloud.githubusercontent.com/assets/4182573/19819752/16b81464-9d24-11e6-857d-4ced982511af.png">

**Comment by d4mation** [comment]
@joelworsham It only happens on iPad breakpoints, so I'm thinking some creative use of the column classes will fix it. This was next on my list as I just fixed #18

**Comment by d4mation** [comment]
Tweaked it a bit just now locally and the big problem comes with the amount of text there.

The Blockquote in the Mock seems to be following its own Column-Width rather than being in the same Column as the above content like it is on the site (The Blockquote is wider in the mock than the Content above). On the site these are controlled by the same WYSIWYG. This means the Blockquote is narrower and taller on the site than the Mock.

By adjusting the CSS Width of the Image and its placement on the edge I was able to come up with the following. It is not perfect, but it is much better than the current Issue. (The Blog Posts in between the two sections don't show up on my local instance, don't worry about that empty gap)

![image](https://cloud.githubusercontent.com/assets/7770631/19819895/bd6acf22-9d24-11e6-98fe-3dbfcc1ea05b.png)

**Comment by joelworsham** [comment]
I'd say that looks great! My initial design never intended for the picture of pat to be any shorter than the section itself, or at least not by much.

**Comment by brashrebel** [comment]
I'm meeting with Pat right now and the picture still appears small on full screens. It looks nice and big in the original mocks but is small on the live site now. Can we adjust that please?
